import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shop App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link className={styles.card} href="/builder">
          <a>Go to Builder</a>
        </Link>

        <h1 className={styles.about}>
          Welcome to Uke Engraver written in NextJS and Flutter
        </h1>
      </main>
    </div>
  );
};

export default Home;
